// Mock data for development without Supabase
// Remove this file once Supabase is connected

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);
const hoursAgo = (n: number) => new Date(now.getTime() - n * 60 * 60 * 1000);
const daysFromNow = (n: number) => new Date(now.getTime() + n * 24 * 60 * 60 * 1000);

export const mockEngagements = [
  {
    id: "eng-1",
    name: "AI Workflow Dashboard",
    stage: "build" as const,
    stageEnteredAt: daysAgo(12),
    dealValue: "12000",
    expectedCloseDate: daysFromNow(30).toISOString().split("T")[0],
    probability: "80",
    source: "website" as const,
    maintenanceOptedIn: true,
    maintenanceMonthlyFee: "800",
    maintenanceNextCheckin: null,
    tags: ["AI", "Dashboard", "Workflow automation"],
    createdAt: daysAgo(74),
    companyId: "comp-1",
    companyName: "The Stability Group",
    companyIndustry: "Consulting",
    contactId: "con-1",
    contactName: "Jesse Martinez",
    contactEmail: "jesse@stabilitygroup.com",
    nextActionDueDate: daysAgo(2).toISOString().split("T")[0],
  },
  {
    id: "eng-2",
    name: "Executive Speaker Website",
    stage: "proposal" as const,
    stageEnteredAt: daysAgo(5),
    dealValue: "8500",
    expectedCloseDate: daysFromNow(14).toISOString().split("T")[0],
    probability: "60",
    source: "referral" as const,
    maintenanceOptedIn: false,
    maintenanceMonthlyFee: null,
    maintenanceNextCheckin: null,
    tags: ["Website", "Speaker platform"],
    createdAt: daysAgo(21),
    companyId: "comp-2",
    companyName: "Dr. Bob Nelson",
    companyIndustry: "Executive Coaching",
    contactId: "con-2",
    contactName: "Bob Nelson",
    contactEmail: "bob@drbob.com",
    nextActionDueDate: daysAgo(1).toISOString().split("T")[0],
  },
  {
    id: "eng-3",
    name: "AI Chatbot Integration",
    stage: "discovery" as const,
    stageEnteredAt: daysAgo(3),
    dealValue: null,
    expectedCloseDate: null,
    probability: "30",
    source: "linkedin" as const,
    maintenanceOptedIn: false,
    maintenanceMonthlyFee: null,
    maintenanceNextCheckin: null,
    tags: ["AI", "Chatbot"],
    createdAt: daysAgo(3),
    companyId: "comp-3",
    companyName: "Meridian Labs",
    companyIndustry: "Biotech",
    contactId: "con-3",
    contactName: "Sarah Chen",
    contactEmail: "sarah@meridianlabs.io",
    nextActionDueDate: daysFromNow(2).toISOString().split("T")[0],
  },
  {
    id: "eng-4",
    name: "Inventory Management System",
    stage: "discovery" as const,
    stageEnteredAt: daysAgo(1),
    dealValue: null,
    expectedCloseDate: null,
    probability: null,
    source: "cold" as const,
    maintenanceOptedIn: false,
    maintenanceMonthlyFee: null,
    maintenanceNextCheckin: null,
    tags: [],
    createdAt: daysAgo(1),
    companyId: "comp-4",
    companyName: "Harbor Freight Co",
    companyIndustry: "Logistics",
    contactId: "con-4",
    contactName: "Marcus Rivera",
    contactEmail: "marcus@harborfreight.co",
    nextActionDueDate: null,
  },
  {
    id: "eng-5",
    name: "Analytics Dashboard",
    stage: "discovery" as const,
    stageEnteredAt: daysAgo(4),
    dealValue: null,
    expectedCloseDate: null,
    probability: null,
    source: "inbound" as const,
    maintenanceOptedIn: false,
    maintenanceMonthlyFee: null,
    maintenanceNextCheckin: null,
    tags: [],
    createdAt: daysAgo(4),
    companyId: "comp-5",
    companyName: "Prism Analytics",
    companyIndustry: "Data Analytics",
    contactId: "con-5",
    contactName: "Aisha Patel",
    contactEmail: "aisha@prismanalytics.com",
    nextActionDueDate: null,
  },
  {
    id: "eng-6",
    name: "Client Portal Redesign",
    stage: "building_mvp" as const,
    stageEnteredAt: daysAgo(6),
    dealValue: null,
    expectedCloseDate: null,
    probability: null,
    source: null,
    maintenanceOptedIn: false,
    maintenanceMonthlyFee: null,
    maintenanceNextCheckin: null,
    tags: [],
    createdAt: daysAgo(6),
    companyId: "comp-6",
    companyName: "Apex Financial",
    companyIndustry: "Finance",
    contactId: "con-6",
    contactName: "David Kim",
    contactEmail: "dkim@apexfinancial.com",
    nextActionDueDate: null,
  },
  {
    id: "eng-7",
    name: "E-Commerce Platform",
    stage: "closed_won" as const,
    stageEnteredAt: daysAgo(10),
    dealValue: "25000",
    expectedCloseDate: daysAgo(10).toISOString().split("T")[0],
    probability: "100",
    source: "referral" as const,
    maintenanceOptedIn: true,
    maintenanceMonthlyFee: "1200",
    maintenanceNextCheckin: daysFromNow(30).toISOString().split("T")[0],
    tags: ["E-Commerce", "Full build"],
    createdAt: daysAgo(90),
    companyId: "comp-7",
    companyName: "Summit Retail",
    companyIndustry: "Retail",
    contactId: "con-7",
    contactName: "Linda Torres",
    contactEmail: "linda@summitretail.com",
    nextActionDueDate: null,
  },
  {
    id: "eng-8",
    name: "Mobile App Prototype",
    stage: "closed_lost" as const,
    stageEnteredAt: daysAgo(15),
    dealValue: "18000",
    expectedCloseDate: daysAgo(20).toISOString().split("T")[0],
    probability: "0",
    source: "linkedin" as const,
    maintenanceOptedIn: false,
    maintenanceMonthlyFee: null,
    maintenanceNextCheckin: null,
    tags: ["Mobile", "Prototype"],
    createdAt: daysAgo(60),
    companyId: "comp-8",
    companyName: "Vantage Health",
    companyIndustry: "Healthcare",
    contactId: "con-8",
    contactName: "Ryan Cho",
    contactEmail: "ryan@vantagehealth.com",
    nextActionDueDate: null,
  },
];

export const mockTimeline = {
  "eng-1": [
    {
      id: "int-1",
      type: "meeting" as const,
      content:
        "Check-in meeting — Reviewed sprint 3 progress. Jesse wants mobile-first for the dashboard. Agreed on 2-week timeline for responsive redesign.",
      scheduledAt: daysAgo(1),
      createdAt: daysAgo(1),
      authorName: "Nick",
    },
    {
      id: "int-2",
      type: "note" as const,
      content:
        "Sent MVP v2 for review. Waiting on feedback re: onboarding flow changes.",
      scheduledAt: null,
      createdAt: daysAgo(4),
      authorName: "Nick",
    },
    {
      id: "int-3",
      type: "action" as const,
      content: "MVP v2 deployed to staging. All 4 core workflows functional.",
      scheduledAt: null,
      createdAt: daysAgo(9),
      authorName: "Co-founder 2",
    },
    {
      id: "int-4",
      type: "meeting" as const,
      content:
        "Sprint 2 review. Client approved dashboard design. Flagged: needs CSV export for reporting.",
      scheduledAt: daysAgo(15),
      createdAt: daysAgo(15),
      authorName: "Co-founder 3",
    },
    {
      id: "int-5",
      type: "stage_change" as const,
      content: "Stage changed: proposal → build",
      scheduledAt: null,
      createdAt: daysAgo(30),
      authorName: "Nick",
    },
    {
      id: "int-6",
      type: "meeting" as const,
      content:
        "Discovery call — Initial requirements gathering. Pain points: manual data entry, no visibility into team activity.",
      scheduledAt: daysAgo(60),
      createdAt: daysAgo(60),
      authorName: "Nick",
    },
    {
      id: "int-7",
      type: "note" as const,
      content:
        "Lead created — Inbound from website CTA. Jesse booked via Calendly.",
      scheduledAt: null,
      createdAt: daysAgo(74),
      authorName: "Co-founder 2",
    },
  ],
  "eng-2": [
    {
      id: "int-20",
      type: "note" as const,
      content:
        "Dr. Bob wants a speaker page with booking, testimonials, and a media kit download. Loves clean, professional aesthetic.",
      scheduledAt: null,
      createdAt: daysAgo(3),
      authorName: "Nick",
    },
    {
      id: "int-21",
      type: "meeting" as const,
      content:
        "Discovery call — Bob has 30+ years of executive coaching experience. Needs a modern web presence to book more speaking gigs.",
      scheduledAt: daysAgo(14),
      createdAt: daysAgo(14),
      authorName: "Co-founder 3",
    },
    {
      id: "int-22",
      type: "note" as const,
      content: "Lead from referral — Bob was recommended by a mutual contact.",
      scheduledAt: null,
      createdAt: daysAgo(21),
      authorName: "Nick",
    },
  ],
  "eng-3": [
    {
      id: "int-30",
      type: "meeting" as const,
      content:
        "Discovery call — Sarah needs an AI chatbot for their lab portal. Wants it to answer questions about their research papers and datasets.",
      scheduledAt: hoursAgo(6),
      createdAt: hoursAgo(6),
      authorName: "Co-founder 2",
    },
    {
      id: "int-31",
      type: "note" as const,
      content:
        "Inbound lead from LinkedIn post about AI consulting. Sarah reached out directly.",
      scheduledAt: null,
      createdAt: daysAgo(3),
      authorName: "Nick",
    },
  ],
};

export const mockActions = {
  "eng-1": [
    {
      id: "act-1",
      description: "Follow up on MVP v2 feedback",
      priority: "urgent" as const,
      dueDate: daysAgo(2).toISOString().split("T")[0],
      completed: false,
      completedAt: null,
      ownerName: "Nick",
      ownerId: "user-1",
    },
    {
      id: "act-2",
      description: "Start responsive redesign",
      priority: "high" as const,
      dueDate: daysFromNow(3).toISOString().split("T")[0],
      completed: false,
      completedAt: null,
      ownerName: "Co-founder 2",
      ownerId: "user-2",
    },
    {
      id: "act-3",
      description: "Add CSV export feature",
      priority: "normal" as const,
      dueDate: daysFromNow(11).toISOString().split("T")[0],
      completed: false,
      completedAt: null,
      ownerName: "Co-founder 3",
      ownerId: "user-3",
    },
    {
      id: "act-4",
      description: "Set up staging environment",
      priority: "low" as const,
      dueDate: daysAgo(20).toISOString().split("T")[0],
      completed: true,
      completedAt: daysAgo(18),
      ownerName: "Nick",
      ownerId: "user-1",
    },
  ],
  "eng-2": [
    {
      id: "act-10",
      description: "Send revised proposal with maintenance pricing",
      priority: "urgent" as const,
      dueDate: daysAgo(1).toISOString().split("T")[0],
      completed: false,
      completedAt: null,
      ownerName: "Nick",
      ownerId: "user-1",
    },
  ],
  "eng-3": [
    {
      id: "act-20",
      description: "Send follow-up email with scope options",
      priority: "high" as const,
      dueDate: daysFromNow(2).toISOString().split("T")[0],
      completed: false,
      completedAt: null,
      ownerName: "Co-founder 2",
      ownerId: "user-2",
    },
  ],
};

export const mockRecentActivity = [
  {
    id: "act-r1",
    type: "meeting" as const,
    content:
      "Check-in meeting — Sprint 3 review. Jesse wants mobile-first dashboard.",
    createdAt: hoursAgo(2),
    authorName: "Nick",
    engagementName: "AI Workflow Dashboard",
    companyName: "The Stability Group",
    engagementId: "eng-1",
  },
  {
    id: "act-r2",
    type: "meeting" as const,
    content:
      "Discovery call — Sarah needs AI chatbot for lab portal.",
    createdAt: hoursAgo(6),
    authorName: "Co-founder 2",
    engagementName: "AI Chatbot Integration",
    companyName: "Meridian Labs",
    engagementId: "eng-3",
  },
  {
    id: "act-r3",
    type: "note" as const,
    content:
      "Dr. Bob wants speaker page with booking, testimonials, and media kit.",
    createdAt: daysAgo(3),
    authorName: "Nick",
    engagementName: "Executive Speaker Website",
    companyName: "Dr. Bob Nelson",
    engagementId: "eng-2",
  },
  {
    id: "act-r4",
    type: "note" as const,
    content: "Sent MVP v2 for review. Waiting on feedback re: onboarding flow.",
    createdAt: daysAgo(4),
    authorName: "Nick",
    engagementName: "AI Workflow Dashboard",
    companyName: "The Stability Group",
    engagementId: "eng-1",
  },
  {
    id: "act-r5",
    type: "stage_change" as const,
    content: "Stage changed: lead → discovery",
    createdAt: daysAgo(3),
    authorName: "Co-founder 2",
    engagementName: "AI Chatbot Integration",
    companyName: "Meridian Labs",
    engagementId: "eng-3",
  },
];

export const mockContacts = [
  {
    id: "con-1",
    name: "Jesse Martinez",
    email: "jesse@stabilitygroup.com",
    phone: "(415) 555-0142",
    role: "CEO",
    companyName: "The Stability Group",
    companyId: "comp-1",
    lastInteraction: hoursAgo(2).toISOString(),
  },
  {
    id: "con-2",
    name: "Bob Nelson",
    email: "bob@drbob.com",
    phone: "(212) 555-0198",
    role: "Speaker / Author",
    companyName: "Dr. Bob Nelson",
    companyId: "comp-2",
    lastInteraction: daysAgo(3).toISOString(),
  },
  {
    id: "con-3",
    name: "Sarah Chen",
    email: "sarah@meridianlabs.io",
    phone: "(650) 555-0173",
    role: "Head of Research",
    companyName: "Meridian Labs",
    companyId: "comp-3",
    lastInteraction: hoursAgo(6).toISOString(),
  },
  {
    id: "con-4",
    name: "Marcus Rivera",
    email: "marcus@harborfreight.co",
    phone: null,
    role: "Operations Director",
    companyName: "Harbor Freight Co",
    companyId: "comp-4",
    lastInteraction: null,
  },
  {
    id: "con-5",
    name: "Aisha Patel",
    email: "aisha@prismanalytics.com",
    phone: "(408) 555-0216",
    role: "CTO",
    companyName: "Prism Analytics",
    companyId: "comp-5",
    lastInteraction: null,
  },
  {
    id: "con-6",
    name: "David Kim",
    email: "dkim@apexfinancial.com",
    phone: null,
    role: "VP Engineering",
    companyName: "Apex Financial",
    companyId: "comp-6",
    lastInteraction: null,
  },
  {
    id: "con-7",
    name: "Linda Torres",
    email: "linda@summitretail.com",
    phone: "(305) 555-0187",
    role: "CEO",
    companyName: "Summit Retail",
    companyId: "comp-7",
    lastInteraction: daysAgo(10).toISOString(),
  },
  {
    id: "con-8",
    name: "Ryan Cho",
    email: "ryan@vantagehealth.com",
    phone: "(617) 555-0234",
    role: "Product Manager",
    companyName: "Vantage Health",
    companyId: "comp-8",
    lastInteraction: daysAgo(15).toISOString(),
  },
];

export const mockMetrics = {
  overdueActions: 2,
  meetingsToday: 0,
  activeEngagements: 8,
};

export const mockPipelineCounts: Record<string, number> = {
  discovery: 3,
  building_mvp: 1,
  proposal: 1,
  build: 1,
  deliver: 0,
  maintain: 0,
  closed_won: 1,
  closed_lost: 1,
};
